packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  expo: 53.0.13
  react-native: 0.79.4
  react: 19.0.0
  "@types/react": ~19.1.8
  react-docgen-typescript: 2.2.2
  typescript: ~5.8.3
  "@tanstack/react-query": ^5.90.10

  # Babel
  "@babel/core": ^7.28.5
  babel-plugin-syntax-hermes-parser: ^0.29.1
  babel-plugin-module-resolver: ^5.0.2

  # Credo / Agent / SSI
  credo-ts-didweb-anoncreds: 0.0.1-alpha.14
  rxjs: ^7.8.1
  query-string: ^8.1.0
  "@animo-id/eudi-wallet-functionality": 0.0.0-alpha-20250917090914
  "@animo-id/expo-ausweis-sdk": 0.0.1-alpha.14
  "@animo-id/expo-secure-environment": 0.1.5
  "@animo-id/expo-digital-credentials-api": 0.4.0
  "@animo-id/expo-mdoc-data-transfer": 0.1.4-alpha.3
  "@animo-id/mdoc": 0.5.2
  "@unimodules/react-native-adapter": ./noop
  "@unimodules/core": ./noop
  "@openid4vc/oauth2": ^0.4.0
  "@openid4vc/openid4vp": ^0.4.0
  "@openid4vc/openid4vci": ^0.4.0
  "@openid4vc/utils": ^0.4.0
  isomorphic-webcrypto: npm:@sphereon/isomorphic-webcrypto
  fast-text-encoding: ^1.0.6
  "@types/fast-text-encoding": ^1.0.3
  "@credo-ts/anoncreds": 0.6.1-alpha-20251205132807
  "@credo-ts/askar": 0.6.1-alpha-20251205132807
  "@credo-ts/cheqd": 0.6.1-alpha-20251205132807
  "@credo-ts/core": 0.6.1-alpha-20251205132807
  "@credo-ts/openid4vc": 0.6.1-alpha-20251205132807
  "@credo-ts/question-answer": 0.6.1-alpha-20251205132807
  "@credo-ts/react-native": 0.6.1-alpha-20251205132807
  "@credo-ts/didcomm": 0.6.1-alpha-20251205132807
  "@hyperledger/anoncreds-react-native": 0.3.4
  "@hyperledger/anoncreds-shared": 0.3.4
  "@openwallet-foundation/askar-react-native": 0.4.3
  "@openwallet-foundation/askar-shared": 0.4.3
  buffer: 6.0.3
  "@astronautlabs/jsonpath": ^1.1.2
  
  # React Native
  "@react-native-community/netinfo": ~11.4.1
  react-native-heroicons: ^4.0.0
  "@react-native-masked-view/masked-view": 0.3.2
  react-native-argon2: ^3.0.0
  react-native-keychain: ^8.2.0
  react-native-get-random-values: ~1.11.0
  react-native-gesture-handler: ~2.24.0
  react-native-reanimated: ~3.17.4
  react-native-safe-area-context: 5.4.0
  react-native-screens: ~4.11.1
  react-native-svg: 15.11.2
  "@react-navigation/native": ^7.1.19
  react-native-fs: ^2.20.0
  react-native-mmkv: ^3.3.0
  react-native-qrcode-svg: ^6.3.20
  react-native-reanimated-carousel: ^4.0.3
  burnt: ^0.13.0
  "@react-native-community/blur": ^4.3.2
  "@gorhom/bottom-sheet": ^5
  react-native-edge-to-edge: ^1.6.0
  react-native-vision-camera: ^4.7.3

  # Expo
  expo-crypto: ^15.0.7
  expo-standard-web-crypto: 2.1.4
  expo-application: ~6.1.5
  expo-asset: ~11.1.6
  expo-blur: ~14.1.5
  expo-constants: ~17.1.6
  expo-dev-client: ~5.2.2
  expo-device: ~7.1.4
  expo-font: ~13.3.2
  expo-haptics: ~14.1.4
  expo-image: ~2.3.1
  expo-image-manipulator: ~13.1.7
  expo-linear-gradient: ~14.1.5
  expo-linking: ~7.1.6
  expo-router: ~5.1.2
  expo-secure-store: ~14.2.3
  expo-splash-screen: ~0.30.9
  expo-system-ui: ~5.0.9
  expo-updates: ~0.28.15
  expo-web-browser: ~14.2.0
  expo-build-properties: ~0.14.8
  expo-localization: ~16.1.6
  "@expo-google-fonts/open-sans": ^0.4.2
  "@expo-google-fonts/raleway": ^0.4.2
  "@expo/config-plugins": 10.1.2

  # Tamagui
  "@tamagui/animations-react-native": 1.132.18
  "@tamagui/font-inter": 1.132.18
  "@tamagui/shorthands": 1.132.18
  "@tamagui/themes": 1.132.18
  "@tamagui/toast": 1.132.18
  "@tamagui/react-native-media-driver": 1.132.18
  "@tamagui/colors": 1.132.18
  "@tamagui/lucide-icons": 1.132.18
  "@tamagui/babel-plugin": 1.132.18
  tamagui: 1.132.18
