packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  expo: ^54.0.27
  react-native: ^0.81.5
  react: 19.1.0
  "@types/react": ~19.1.0
  typescript: ~5.9.3
  "@tanstack/react-query": ^5.90.14

  # Babel
  "@babel/core": ^7.28.5
  babel-plugin-syntax-hermes-parser: ^0.32.1
  babel-plugin-module-resolver: ^5.0.2

  # Credo / Agent / SSI
  credo-ts-didweb-anoncreds: 0.0.2-alpha.2
  rxjs: ^7.8.1
  query-string: ^9.3.1
  "@animo-id/eudi-wallet-functionality": 0.0.0-alpha-20250917090914
  "@animo-id/expo-ausweis-sdk": 0.0.1-alpha.14
  "@animo-id/expo-secure-environment": 0.1.5
  "@animo-id/expo-digital-credentials-api": 0.4.0
  "@animo-id/expo-mdoc-data-transfer": 0.1.4-alpha.3
  "@animo-id/mdoc": 0.5.2
  "@openid4vc/oauth2": ^0.4.0
  "@openid4vc/openid4vp": ^0.4.0
  "@openid4vc/openid4vci": ^0.4.0
  "@openid4vc/utils": ^0.4.0
  fast-text-encoding: ^1.0.6
  "@types/fast-text-encoding": ^1.0.3
  "@credo-ts/anoncreds": 0.6.2-alpha-20251211125344
  "@credo-ts/askar": 0.6.2-alpha-20251211125344
  "@credo-ts/cheqd": 0.6.2-alpha-20251211125344
  "@credo-ts/core": 0.6.2-alpha-20251211125344
  "@credo-ts/openid4vc": 0.6.2-alpha-20251211125344
  "@credo-ts/question-answer": 0.6.2-alpha-20251211125344
  "@credo-ts/react-native": 0.6.2-alpha-20251211125344
  "@credo-ts/didcomm": 0.6.2-alpha-20251211125344
  "@hyperledger/anoncreds-react-native": 0.3.4
  "@hyperledger/anoncreds-shared": 0.3.4
  "@openwallet-foundation/askar-react-native": 0.5.0-alpha-20251222150428
  "@openwallet-foundation/askar-shared": 0.5.0-alpha-20251222150428
  buffer: 6.0.3
  "@astronautlabs/jsonpath": ^1.1.2
  
  # React Native
  react-native-heroicons: ^4.0.0
  "@react-native-masked-view/masked-view": 0.3.2
  "@react-native-picker/picker": ^2.11.1
  react-native-keychain: ^10.0.0
  react-native-get-random-values: ^2.0.0
  react-native-gesture-handler: ^2.29.1
  react-native-reanimated: ^4.2.0
  react-native-safe-area-context: ^5.6.2
  react-native-screens: ^4.18.0
  react-native-svg: ^15.15.1
  "@react-navigation/native": ^7.1.26
  # React Native FS is not maintained, and doesn't support new Arch
  # this seems to be the best maintained fork. We might want to switch
  # to Expo FileSystem, but Credo depends on react-native-fs
  "react-native-fs": "npm:@dr.pogodin/react-native-fs@^2.36.1"
  react-native-mmkv: ^4.1.0
  react-native-qrcode-svg: ^6.3.21
  react-native-reanimated-carousel: ^4.0.3
  burnt: ^0.13.0
  "@react-native-community/blur": ^4.3.2
  "@gorhom/bottom-sheet": ^5.2.8
  react-native-edge-to-edge: ^1.7.0

  # Expo
  expo-crypto: ^15.0.8
  expo-camera: ^16.1.10
  expo-network: ~8.0.8
  expo-application: ^7.0.8
  expo-asset: ^12.0.11
  expo-blur: ^15.0.8
  expo-constants: ^18.0.11
  expo-dev-client: ^6.0.20
  expo-device: ^8.0.10
  expo-font: ^14.0.10
  expo-haptics: ^15.0.8
  expo-image: ^3.0.11
  expo-image-manipulator: ^14.0.8
  expo-linear-gradient: ^15.0.8
  expo-linking: ^8.0.10
  expo-router: ^6.0.17
  expo-secure-store: ^15.0.8
  expo-splash-screen: ^31.0.12
  expo-system-ui: ^6.0.9
  expo-updates: ^29.0.14
  expo-web-browser: ^15.0.10
  expo-build-properties: ^1.0.10
  expo-localization: ^17.0.8
  "@expo-google-fonts/open-sans": ^0.4.2
  "@expo-google-fonts/raleway": ^0.4.2

  # Tamagui
  "@tamagui/animations-react-native": 1.139.2
  "@tamagui/font-inter": 1.139.2
  "@tamagui/shorthands": 1.139.2
  "@tamagui/themes": 1.139.2
  "@tamagui/toast": 1.139.2
  "@tamagui/react-native-media-driver": 1.139.2
  "@tamagui/colors": 1.139.2
  "@tamagui/lucide-icons": 1.139.2
  "@tamagui/babel-plugin": 1.139.2
  tamagui: 1.139.2