export const HEADER_STATUS_BAR_HEIGHT = 56
export const BASE_CREDENTIAL_CARD_HEIGHT = 196
export const CREDENTIAL_TOP_INFO_OFFSET = 56
export const CREDENTIAL_TOP_INFO_HEIGHT = 64
export const HEADER_TITLE_TEXT_HEIGHT = 38
