name: Continous Deployment (Paradym Wallet Sdk)

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-stable:
    runs-on: ubuntu-latest
    name: Release Stable
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          pr-title: "chore(release): new version"
          commit-message: "chore(release): new version"
          publish-script: pnpm release:sdk
          version-script: pnpm changeset-version:sdk

  release-unstable:
    runs-on: ubuntu-latest
    name: Release Unstable
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create unstable release
        run: |
          # this ensures there's always a patch release created
          cat << 'EOF' > .changeset/snapshot-template-changeset.md
          ---
          '@paradym/wallet-sdk': patch
          ---

          snapshot release
          EOF

          pnpm changeset version --snapshot alpha
          pnpm style:fix
          pnpm build
          pnpm changeset publish --tag alpha
